name: Building app

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  app-build:
    name: Build app
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "binaries"

  tests:
    name: Functional tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - app-build

    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: Download app binary
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: bin

    - name: Install Speculos
      run: |
        sudo apt-get update && sudo apt-get install -y qemu-user-static
        pip install --extra-index-url https://test.pypi.org/simple/ speculos

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Installing JS dependencies
      run: |
        cd tests
        npm install

    - name: Running tests
      run: ./tests/node_modules/.bin/mocha tests/ --exit --require tests/hooks.js --config tests/.mocharc.js "$@"
      env:
        LEDGER_APP: bin/nanos/bin/app.elf
